# Config file for automatic testing at travis-ci.com

language: python
python:
  - 3.8
  - 3.7
  - 3.6
  - 3.5

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
#install: pip3 install -U tox-travis -r requirements_test.txt
install: pip3 install -r requirements_test.txt

# Command to run tests, e.g. python setup.py test
script: tox


